version: '3.4'

services:
  accountdb:
    container_name: accountdb
    environment:
      SA_PASSWORD: "12345onlineshopaccountdb"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"

  basketdb:
    container_name: basketdb
    environment:
      SA_PASSWORD: "12345onlineshopbasketdb"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1435:1433"

  productdb:
    container_name: productdb
    environment:
      SA_PASSWORD: "12345onlineshopproductdb"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1438:1433"

  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "12345onlineshoporderdb"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1437:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  account.api:
    container_name: account.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ConnectionStringDocker=Server=accountdb;Port=1434;Database=AccountApiDB;User Id=sa;Password=12345onlineshopaccountdb;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - accountdb
      - rabbitmq
    ports:
      - "7000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ConnectionStringDocker=Server=basketdb;Port=1435;Database=BasketApiDB;User Id=sa;Password=12345onlineshopbasketdb;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "7001:80"

  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ConnectionStringDocker=Server=productdb;Port=1435;Database=ProductApiDB;User Id=sa;Password=12345onlineshopproductdb;"
      - "GrpcSettings:ProductUrlDocker=product.grpc"
    depends_on:
      - productdb
    ports:
      - "7004:80"

  product.grpc:
    container_name: product.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:ConnectionStringDocker=Server=productdb;Port=1435;Database=ProductApiDB;User Id=sa;Password=12345onlineshopproductdb;"
    ports:
      - "8005:80"
      - "8006:443"
    depends_on:
      - productdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ConnectionStringDocker=Server=orderdb;Port=1437;Database=OrderApiDB;User Id=sa;Password=12345onlineshoporderdb;"
    depends_on:
      - orderdb
    ports:
      - "7003:80"


  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - product.api
      - account.api
      - order.api
      - basket.api
    ports:
      - "2010:80"

